"""Add ForeignKey to users.role_id

Revision ID: fed1c858f386
Revises: aba738dccd85
Create Date: 2026-09-28 10:15:24.787563

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fed1c858f386"
down_revision: str | Sequence[str] | None = "aba738dccd85"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_users_role_id_roles", "users", "roles", ["role_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_users_role_id_roles", "users", type_="foreignkey")
    # ### end Alembic commands ###
